--- #YAML:1.0
name:               Data-Dumper
version:            2.131
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
resources:
    bugtracker:   http://rt.perl.org/perlbug/
    MailingList:  http://lists.cpan.org/showlist.cgi?name=perl5-porters
    repository:   git://perl5.git.perl.org/perl.git perl-git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
