--- #YAML:1.0
name:                Tree-DAG_Node
version:             1.06
abstract:            (super)class for representing nodes in a tree
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Carp:                          0
    strict:                        0
    vars:                          0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - David Hand, <cogent@cpan.org>
