---
abstract: 'apparently run a function in a higher stack frame'
author:
  - 'Michael Schwern <mschwern@cpan.org>'
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  Exporter: 0
  File::Find: 0
  File::Temp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300005, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sub-Uplevel
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  Sub::Uplevel:
    file: lib/Sub/Uplevel.pm
    version: 0.24
requires:
  Carp: 0
  constant: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Sub-Uplevel
  homepage: https://github.com/dagolden/sub-uplevel
  repository: https://github.com/dagolden/sub-uplevel.git
version: 0.24
